version: '3.7'

services:

  redis:
    image: redis:7.0.0-alpine
    volumes:
      - redis-data:/data
    ports:
      - 127.0.0.1:6379:6379
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
